# -*- coding: utf-8 -*-
"""
Created on Wed Oct  5 15:37:39 2022

@author: iant
"""


observation_cycle = [
    {"daynight":"n", "status":"on", "filter_cycle":"night_123d"},
    # {"daynight":"d", "status":"on", "filter_cycle":"day_2d4d"},
    # {"daynight":"n", "status":"on", "filter_cycle":"night_123d"},
    # {"daynight":"d", "status":"on", "filter_cycle":"day_2d4d"},
    # {"daynight":"n", "status":"on", "filter_cycle":"night_123d"},
    # {"daynight":"d", "status":"on", "filter_cycle":"day_2d4d"},
    # {"daynight":"n", "status":"on", "filter_cycle":"night_123d"},
    # {"daynight":"d", "status":"on", "filter_cycle":"day_2d4d"},
    # {"daynight":"n", "status":"on", "filter_cycle":"night_123d"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"on", "filter_cycle":"night_123d"},
    # {"daynight":"d", "status":"on", "filter_cycle":"day_2d4d"},
    # {"daynight":"n", "status":"on", "filter_cycle":"night_123d"},
    # {"daynight":"d", "status":"on", "filter_cycle":"day_2d4d"},
    # {"daynight":"n", "status":"on", "filter_cycle":"night_123d"},
    # {"daynight":"d", "status":"on", "filter_cycle":"day_2d4d"},
    # {"daynight":"n", "status":"on", "filter_cycle":"night_123d"},
    # {"daynight":"d", "status":"on", "filter_cycle":"day_2d4d"},
    # {"daynight":"n", "status":"on", "filter_cycle":"night_123d"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
    # {"daynight":"n", "status":"off"},
    # {"daynight":"d", "status":"off"},
]

