# -*- coding: utf-8 -*-
"""
Created on Mon Sep 12 09:45:05 2022

@author: iant

VENSPEC-H OPERATIONS PLAN

HIGH DATA RATE:
    DAYSIDE:
        MINIMAL ACROSS-TRACK BINNING
        SHORT INTEGRATION TIME - MAY NEED MULTIPLE ACCUMULATIONS?
        DARK FRAMES EVERY N MEASUREMENTS
    NIGHTSIDE:
        BINNED ACROSS-TRACK
        LONG INTEGRATION TIME - SINGLE ACCUMULATION
        DARK FRAMES EVERY N MEASUREMENTS

"""


ops_dict = {
    "high":{
        ""}}